/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String forma = args[0];
        int tamanho1 = Integer.parseInt(args[1]);

        if (args.length < 2) {
            System.out.println("Você deve digitar pelo menos um tamanho da forma");
            return;
        }


        switch (forma) {
            case "triangulo" -> {

                int espaços = tamanho1 - 1;
                for (int i = 1; i <= tamanho1; i++) {
                    System.out.println(" ".repeat(espaços--) + "*".repeat(i));
                }
                // tamanho de espaços decresce enquanto tamanho de * aumenta
            }
            case "losango" -> {

                if (tamanho1 % 2 == 0) {
                    System.out.println("O tamanho do losango deve ser ímpar.");
                    return;
                }

                int espaços = tamanho1 / 2; //calculo dos espaços


                for (int i = 1; i <= tamanho1; i += 2) {
                    System.out.println(" ".repeat(espaços) + "*".repeat(i));
                    espaços--;
                } // espaços diminui linearmente enquanto * aumenta de 2 em 2
                espaços = 1; // para não dar contador negativo por causa do loop

                for (int i = tamanho1 - 2; i > 0; i -= 2) {
                    System.out.println(" ".repeat(espaços) + "*".repeat(i));
                    espaços++;
                }
                // caminho inverso
            }
            case "retangulo" -> {
                if (args.length < 3) {
                    System.out.println("Digite o segundo lado do retângulo");
                    return;
                }
                int tamanho2 = Integer.parseInt(args[2]);

                System.out.println("*".repeat(tamanho2)); //lado de cima

                for (int i = 0; i < tamanho1 - 2; i++) {
                    System.out.println("*" + " ".repeat(tamanho2 - 2) + "*");
                } //lados laterais, deixando um espaço com - 2 por conta dos asteristicos

                System.out.println("*".repeat(tamanho2)); //lado de baixo

            }
            default -> System.out.println("Forma Inválida, Use, Triangulo, Retangulo ou losango");
        }
        return;
    }
}