/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Random;

public class App {
    public static void main(String[] args) {
        String[][] tabuleiro = new String[10][10];
        for (int i = 0; i < tabuleiro.length; i++) {
            for (int j = 0; j < tabuleiro[i].length; j++) {
                tabuleiro[i][j] = ".";
            }
        }

        String[] navios = new String[]{"P", "E", "C", "S", "N"};
        int[] tamanhos = new int[]{5, 4, 3, 3, 2};

        for (int j = 0; j < navios.length; j++) {
            boolean loop = true;
            Random r = new Random();
            while (loop) {
                int linha = r.nextInt(10);
                int coluna = r.nextInt(10);
                int HouV = r.nextInt(2); // 1 = horizontal, 0 = vertical
                boolean lado = HouV == 1;

                if (lado) { // Horizontal
                    if (tamanhos[j] <= (10 - coluna)) { // Verifica se cabe no tabuleiro
                        boolean espacoLivre = true;
                        for (int i = coluna; i < (coluna + tamanhos[j]); i++) {
                            if (!tabuleiro[linha][i].equals(".")) { // Verifica se já está ocupado
                                espacoLivre = false;
                                break;
                            }
                        }
                        if (espacoLivre) {
                            for (int i = coluna; i < (coluna + tamanhos[j]); i++) {
                                tabuleiro[linha][i] = navios[j];
                            }
                            loop = false; // Sai do loop após posicionar o navio
                        }
                    }
                } else { // Vertical
                    if (tamanhos[j] <= (10 - linha)) { // Verifica se cabe no tabuleiro
                        boolean espacoLivre = true;
                        for (int i = linha; i < (linha + tamanhos[j]); i++) {
                            if (!tabuleiro[i][coluna].equals(".")) { // Verifica se já está ocupado
                                espacoLivre = false;
                                break;
                            }
                        }
                        if (espacoLivre) {
                            for (int i = linha; i < (linha + tamanhos[j]); i++) {
                                tabuleiro[i][coluna] = navios[j];
                            }
                            loop = false; // Sai do loop após posicionar o navio
                        }
                    }
                }
            }
        }

        // Imprime o tabuleiro
        for (int i = 0; i < tabuleiro.length; i++) {
            for (int j = 0; j < tabuleiro[i].length; j++) {
                System.out.print(tabuleiro[i][j]);
                System.out.print(" ");
            }
            System.out.print("\n");
        }
    }
}